fix: "TypeError: Cannot read property 'state'" when preloading
We got the above error message when we tapped back twice from a preloaded
route:

> TypeError: Cannot read property 'state' of undefined
> Stack trace:
> > const { routes, preloadRoutes } = navigation.state;
>
> Line 18, src/getChildNavigation.js

After investigating, it's because `getChildrenNavigationCache` was removing
unmounted routes from the cache, but also inadvertently would remove preloaded
routes that would still persist.

I found this by looking through the stack trace, and:

1.  Saw the following two lines were responsible for passing in the
    `navigation` object

    ```js
    var children = getChildrenNavigationCache(navigation);
    // ...
    getChildNavigation(children[childKey], grandChildKey, ...);
    ```

2.  Looked at `getChildrenNavigationCache` and realized it used `state.routes`
    to determine which routes to keep.

3.  Tried changing the `getChildrenNavigationCache` to also look at
    `preloadRoutes`, and that fixed the bug.